import tile, {randomGrass} from '../utils/makeTiles';

const makeInitialMap = () => ([
  [
    tile(5, 4),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(5, 5),
  ],
  [
    tile(5, 2),
    randomGrass(),
    tile(0, 0),
    tile(0, 1),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    randomGrass(),
    tile(0, 2),
    tile(0, 3),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    tile(4, 4),
    tile(0, 4),
    tile(0, 5),
    tile(1, 4),
    tile(1, 4),
    tile(4, 5),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    tile(4, 2),
    tile(0, 7),
    tile(0, 7),
    tile(0, 7),
    tile(1, 0),
    tile(4, 6),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    tile(1, 2),
    tile(4, 6),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    tile(1, 2),
    tile(4, 6),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 2),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    randomGrass(),
    tile(1, 2),
    tile(4, 6),
    randomGrass(),
    randomGrass(),
    tile(5, 3),
  ],
  [
    tile(5, 0),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(4, 7),
    tile(6, 1),
    tile(6, 0),
    tile(4, 7),
    tile(4, 7),
    tile(5, 1),
  ],
]);

export default makeInitialMap;
